
platform :ios, '9.0'

target 'Neighborly' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Neighborly

source 'https://github.com/CocoaPods/Specs.git'
pod 'Starscream', '~> 3.0.2'
pod 'SendBirdSDK'
pod 'Cloudinary', '~> 2.0'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'GoogleMaps'
  target 'NeighborlyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NeighborlyUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  

end



